/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as PlayersCreateRouteImport } from './routes/players/create'
import { Route as PlayersPlayerIdIndexRouteImport } from './routes/players/$playerId/index'
import { Route as PlayersPlayerIdEditRouteImport } from './routes/players/$playerId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersCreateRoute = PlayersCreateRouteImport.update({
  id: '/players/create',
  path: '/players/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdIndexRoute = PlayersPlayerIdIndexRouteImport.update({
  id: '/players/$playerId/',
  path: '/players/$playerId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdEditRoute = PlayersPlayerIdEditRouteImport.update({
  id: '/players/$playerId/edit',
  path: '/players/$playerId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/players/create': typeof PlayersCreateRoute
  '/players/': typeof PlayersIndexRoute
  '/players/$playerId/edit': typeof PlayersPlayerIdEditRoute
  '/players/$playerId/': typeof PlayersPlayerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/players/create': typeof PlayersCreateRoute
  '/players': typeof PlayersIndexRoute
  '/players/$playerId/edit': typeof PlayersPlayerIdEditRoute
  '/players/$playerId': typeof PlayersPlayerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/players/create': typeof PlayersCreateRoute
  '/players/': typeof PlayersIndexRoute
  '/players/$playerId/edit': typeof PlayersPlayerIdEditRoute
  '/players/$playerId/': typeof PlayersPlayerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/players/create'
    | '/players/'
    | '/players/$playerId/edit'
    | '/players/$playerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/players/create'
    | '/players'
    | '/players/$playerId/edit'
    | '/players/$playerId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/players/create'
    | '/players/'
    | '/players/$playerId/edit'
    | '/players/$playerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PlayersCreateRoute: typeof PlayersCreateRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  PlayersPlayerIdEditRoute: typeof PlayersPlayerIdEditRoute
  PlayersPlayerIdIndexRoute: typeof PlayersPlayerIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/create': {
      id: '/players/create'
      path: '/players/create'
      fullPath: '/players/create'
      preLoaderRoute: typeof PlayersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId/': {
      id: '/players/$playerId/'
      path: '/players/$playerId'
      fullPath: '/players/$playerId/'
      preLoaderRoute: typeof PlayersPlayerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId/edit': {
      id: '/players/$playerId/edit'
      path: '/players/$playerId/edit'
      fullPath: '/players/$playerId/edit'
      preLoaderRoute: typeof PlayersPlayerIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PlayersCreateRoute: PlayersCreateRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  PlayersPlayerIdEditRoute: PlayersPlayerIdEditRoute,
  PlayersPlayerIdIndexRoute: PlayersPlayerIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
